#+title: Proposal notes
#+author: Eric Berquist
#+email: erb74@pitt.edu

The current plan is to write my graduate research proposal on
determination of molecular absolute configuration using machine
learning, specifically determining the relationship between
experimental optical/specific rotation and molecular structure.

* Machine learning: features

Most calculations can use some fancy DFT functional with a triple-zeta basis set, unless otherwise noted.

 - Representation: chemical formula
 - Representation: chemical name
 - Representation: SMILES string
 - Representation: InChI string
 - Raw IR spectra (experimental)
 - Raw IR spectra (calculated)
   - peak positions
   - intensities
 - Difference IR spectra between enantiomers (experimental)
 - Difference IR spectra between enantiomers (calculated)
   - peak positions
   - intensities
 - Optical rotation (experimental)
 - Specific rotation (experimental)

* Machine learning: targets

 - Absolute configuration at each stereocenter

* Questions

** Proposal

*** Proposals are granted based upon the likelihood of their success; this is high-risk, high-reward. How can I guarantee that this will work? Worded differently, what will I do if this doesn't work?

** Machine learning

*** What is the difference between supervised, semi-supervised, and unsupervised learning?

*** Which kind of supervised learning does this proposal constitute?

** Python

** Unsorted

*** What is curly (sp) SMILES?

*** What is the difference between machine learning and deep learning?

*** What is the difference between optical rotation and specific rotation?

*** Where to obtain experimental IR spectra?

**** [[http://osdb.info/][OSDB (Open Spectral Database)]]
     It looks like most molecules present here contain links to original spectra from the NIST Webbook, AIST, (others?).

*** Where to obtain experimental optical rotation values?

**** https://brunl01.users.greyc.fr/CHEMISTRY/


***** Who created this? What organization is this?

***** How should this be cited?

*** Where to obtain experimental specific rotation values?

*** How to choose molecules for training set?

*** How to choose molecules for test set?

*** What is the best data representation for storing stereochemical information?

*** How to invert chirality
From an [[http://sourceforge.net/p/avogadro/feature-requests/126/][Avogadro feature request]]:

We should have an extension which inverts the chirality of selected atoms or molecules.

The code is actually easy -- pick two atoms bonded to a chiral carbon center, and translate each of them using the "skeletontree" code. This will swap positions of the two groups.
(Actually, thinking about it, you probably want to change the bond angle to -1.0*angle.)

* TODO

*** Read Alan Aspuru-Guzik's papers on machine learning for predicting DFT energies

* Timeline
